#ifdef RGB_MATRIX_ENABLE
#  define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_ALPHAS_MODS
#  define RGB_MATRIX_STARTUP_HUE 85
#  define RGB_MATRIX_STARTUP_SAT 135
#  define RGB_MATRIX_STARTUP_VAL 50
#  define RGB_MATRIX_STARTUP_SPD 201

#  define ENABLE_RGB_MATRIX_SOLID_COLOR
#  define ENABLE_RGB_MATRIX_ALPHAS_MODS
#  define ENABLE_RGB_MATRIX_BREATHING
#endif
