BOOTLOADER = atmel-dfu # Elite-C MCU

AUDIO_ENABLE = no
AUTO_SHIFT_ENABLE = no
BOOTMAGIC_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = no
LEADER_ENABLE = no
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = no
OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
SLEEP_LED_ENABLE = no
SPACE_CADET_ENABLE = no
STENO_ENABLE = no
SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = no
TERMINAL_ENABLE = no
UNICODE_ENABLE = no
VELOCIKEY_ENABLE = no
VIA_ENABLE = no
WPM_ENABLE = no

# OLED displays
# OLED_DRIVER = SSD1306
BONGOCAT_ENABLE = no
